# Generated by Django 3.0.6 on 2020-06-02 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='route_from',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='route_to',
            new_name='name',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default='This is a message'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='999-999-999', max_length=100),
            preserve_default=False,
        ),
    ]
