# Generated by Django 3.0.6 on 2020-05-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_from', models.CharField(max_length=100)),
                ('route_to', models.CharField(max_length=100)),
                ('sacco_name', models.CharField(max_length=100)),
                ('morning_fare', models.IntegerField()),
                ('daytime_fare', models.IntegerField()),
                ('evening_fare', models.IntegerField()),
            ],
        ),
    ]
